apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: environment-test-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem