apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: environment-test-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: netapp-nas
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem