kind: PersistentVolume
apiVersion: v1
metadata:
  name: doj-network-share-pv
spec:
  capacity:
    storage: 10Gi
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: doj-network-share
    volumeAttributes:
      source: //205.195.215.199/DOJ
    nodeStageSecretRef:
      name: msft-network-share-credentials
      namespace: sandbox-vlad
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - vers=2.1
    - sec=ntlm
  volumeMode: Filesystem
